### ISSUE TITLE
Publish on Accrescent store

### ISSUE THREAD

**Issue by shuvashish76** [rickymohk/OpenDefault#1]
Would you please consider publishing it on [Accrescent](https://github.com/accrescent/accrescent); an alternative android app store?

See their guide: https://accrescent.app/docs/guide/getting-started/

**Comment by rickymohk** [comment]
I am currently working on publishing it to F-Droid. No plan to publish on other platform so far. Thank you for your suggestion and I may take it into consideration if I see the needs in future.
